import React,{useEffect,useMemo,useState}from'react';
import{Alert,PermissionsAndroid,Platform,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,TextInput,TouchableOpacity,View,useWindowDimensions}from'react-native';
import Voice from'@react-native-voice/voice';
import Tts from'react-native-tts';
import Geolocation from'@react-native-community/geolocation';
import AsyncStorage from'@react-native-async-storage/async-storage';

const NAV=['HOME','CADDIE','BAG','COURSE','MORE'];
const BAG0=[['Driver',230],['3 Wood',210],['5 Wood',195],['4 Iron',180],['5 Iron',170],['6 Iron',160],['7 Iron',150],['8 Iron',140],['9 Iron',130],['Pitching Wedge',115],['Gap Wedge',100],['Sand Wedge',85],['Lob Wedge',70],['Putter',0]];
const LIES=['Tee','Fairway','Light Rough','Rough','Deep Rough','Fairway Bunker','Greenside Bunker'];
const TEES=['Black','Blue','White','Red','Yellow'];
const WIND_DIRS=['HEAD','TAIL','L→R','R→L'];
const PARS=[4,5,4,3,4,4,4,5,4,4,3,4,5,4,5,3,3,4];
const WARM=['Loosen Up','Short Wedges','Mid Irons','Long Club','Driver','Chipping','Putting','Ready'];
const ROUTINES=['Target','Lie','Club','Picture','Commit','Breathe','Reset','Next'];
const PRACTICE=['Wedges','Irons','Driver','Chipping','Bunker','Putting'];
const STORAGE='CADDIEOS_V5_PREMIUM';
const blankTargets=()=>Array.from({length:18},()=>({front:null,center:null,back:null}));
const C={bg:'#071E2D',bg2:'#0A2A3E',panel:'#F2ECDD',panel2:'#E7DECA',navy:'#0A2A43',blue:'#0B7FC0',gold:'#D5AE52',gold2:'#F0CE77',text:'#0C2940',muted:'#687682',line:'#CDBE9E',dark:'#04131E',green:'#D5E2C9',white:'#FFFDF7',success:'#DCE7D5'};
function n(v){return Number(String(v).replace(/[^0-9.-]/g,''))||0}
function carryForUnits(m,u){return u==='METRES'?Math.round(m):Math.round(m*1.09361)}
function windAdjustment(w,u){w=Math.abs(n(w));if(!w)return 0;return u==='METRES'?(w/1.609344)*.75*.9144:w*.75}
function playsLike(d,w,e,l,dir,u){d=Math.max(0,n(d));const lp={Tee:0,Fairway:0,'Light Rough':.015,Rough:.04,'Deep Rough':.07,'Fairway Bunker':.045,'Greenside Bunker':0}[l]||0;d*=1+lp;const wa=windAdjustment(w,u);if(dir==='HEAD')d+=wa;if(dir==='TAIL')d-=wa;d*=1+n(e)/100;return Math.max(0,Math.round(d))}
function nearestClub(target,bag,u){const clubs=bag.filter(x=>x[1]>0).map(x=>[x[0],carryForUnits(x[1],u)]);if(!clubs.length)return['—',0];return clubs.reduce((a,b)=>Math.abs(b[1]-target)<Math.abs(a[1]-target)?b:a)}
function windGuide(w,dir,u){w=Math.abs(n(w));const wu=u==='METRES'?'km/h':'mph';if(!w)return'Calm — play your normal shot.';if(dir==='HEAD')return`Headwind ${w} ${wu} — flight it lower and allow extra club.`;if(dir==='TAIL')return`Tailwind ${w} ${wu} — ball will carry farther; avoid over-clubbing.`;const aim=Math.max(1,Math.round((u==='METRES'?w/1.609344:w)*.6));return`${dir==='L→R'?'Left-to-right':'Right-to-left'} crosswind ${w} ${wu} — start about ${aim} ${u==='METRES'?'m':'yd'} into the wind.`}
function makeAdvice(y,club,lie,w,dir,e,u){const unit=u==='METRES'?'metres':'yards';if(lie==='Greenside Bunker'&&y<=(u==='METRES'?41:45))return`${y<=(u==='METRES'?23:25)?'Lob Wedge':'Sand Wedge'}. Open the face, use the bounce, splash through and commit.`;let t=`Playing ${y} ${unit}. ${club}.`;if(lie!=='Tee'&&lie!=='Fairway')t+=` Allow for ${lie.toLowerCase()}.`;if(n(w))t+=` ${windGuide(w,dir,u)}`;if(n(e)>0)t+=` Uphill ${Math.abs(n(e))} percent.`;if(n(e)<0)t+=` Downhill ${Math.abs(n(e))} percent.`;return t+' Pick the target, picture the shot and commit.'}
function parseSpeech(text,S){const s=text.toLowerCase(),num=rx=>{const m=s.match(rx);return m?m[1]:null};const d=num(/(?:to|target|distance|playing)\s+(\d{2,3})/)||num(/(\d{2,3})\s*(?:yards?|yds?|metres?|meters?)/);if(d)S.setDistance(d);const w=num(/(?:wind|headwind|tailwind)\s*(?:is|at)?\s*(\d{1,2})/)||num(/(\d{1,2})\s*(?:mph|kph|km\/h)/);if(w)S.setWind(w);if(/headwind|into the wind|wind.*head/.test(s))S.setWindDir('HEAD');else if(/tailwind|helping wind|wind.*tail/.test(s))S.setWindDir('TAIL');else if(/left to right|left-to-right|ltr/.test(s))S.setWindDir('L→R');else if(/right to left|right-to-left|rtl/.test(s))S.setWindDir('R→L');const sl=num(/(?:slope|uphill|downhill)\s*(?:is|at)?\s*(\d{1,2})/);if(sl)S.setElev(/downhill/.test(s)?`-${sl}`:sl);if(/deep rough/.test(s))S.setLie('Deep Rough');else if(/light rough/.test(s))S.setLie('Light Rough');else if(/rough/.test(s))S.setLie('Rough');else if(/fairway bunker/.test(s))S.setLie('Fairway Bunker');else if(/greenside bunker|green side bunker/.test(s))S.setLie('Greenside Bunker');else if(/bunker/.test(s))S.setLie('Fairway Bunker');else if(/fairway/.test(s))S.setLie('Fairway');else if(/tee/.test(s))S.setLie('Tee')}
function haversine(a,b,u){if(!a||!b)return null;const R=6371000,r=x=>x*Math.PI/180,dLat=r(b.lat-a.lat),dLon=r(b.lon-a.lon),la1=r(a.lat),la2=r(b.lat);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;const m=2*R*Math.asin(Math.min(1,Math.sqrt(h)));return Math.round(u==='METRES'?m:m*1.09361)}

export default function App(){
 const{width,height}=useWindowDimensions();const compact=height<800||width<390;const ui={compact,width,height};
 const[entered,setEntered]=useState(false),[tab,setTab]=useState('HOME'),[screen,setScreen]=useState(null);
 const[distance,setDistance]=useState('150'),[wind,setWind]=useState('0'),[windDir,setWindDir]=useState('HEAD'),[elev,setElev]=useState('0'),[lie,setLie]=useState('Fairway');
 const[bag,setBag]=useState(BAG0),[course,setCourse]=useState(''),[tee,setTee]=useState('White'),[hole,setHole]=useState('1'),[targets,setTargets]=useState(blankTargets());
 const[scores,setScores]=useState(Array(18).fill('')),[putts,setPutts]=useState(Array(18).fill('')),[notes,setNotes]=useState(Array(18).fill(''));
 const[practice,setPractice]=useState('Wedges'),[shape,setShape]=useState('Straight'),[shotResult,setShotResult]=useState('Good'),[practiceDistance,setPracticeDistance]=useState('50'),[warmDone,setWarmDone]=useState([]),[routineDone,setRoutineDone]=useState([]);
 const[units,setUnits]=useState('METRES'),[player,setPlayer]=useState('Player'),[email,setEmail]=useState(''),[handicap,setHandicap]=useState(''),[listening,setListening]=useState(false),[heard,setHeard]=useState('Tap the microphone and ask your caddie.'),[pendingSpeak,setPendingSpeak]=useState(false);
 const[gps,setGps]=useState(null),[courseInfo,setCourseInfo]=useState({phone:'',email:'',membership:'Members & visitors welcome',cart:'Yes',hire:'Yes',proshop:'Yes',pro:'',overview:''});
 const result=useMemo(()=>{const y=playsLike(distance,wind,elev,lie,windDir,units),c=nearestClub(y,bag,units);return{y,club:c[0],carry:c[1]}},[distance,wind,elev,lie,windDir,bag,units]);
 const caddieText=useMemo(()=>makeAdvice(result.y,result.club,lie,wind,windDir,elev,units),[result.y,result.club,lie,wind,windDir,elev,units]);
 const total=scores.reduce((a,b)=>a+n(b),0),totalPutts=putts.reduce((a,b)=>a+n(b),0),played=scores.filter(Boolean).length,toPar=scores.reduce((a,v,i)=>a+(v?n(v)-PARS[i]:0),0);
 const currentTarget=targets[Math.min(17,Math.max(0,n(hole)-1))]||{},gpsPoint=gps?{lat:Number(gps.lat),lon:Number(gps.lon)}:null;
 const targetDistances={front:haversine(gpsPoint,currentTarget.front,units),center:haversine(gpsPoint,currentTarget.center,units),back:haversine(gpsPoint,currentTarget.back,units)};
 useEffect(()=>{(async()=>{try{const raw=await AsyncStorage.getItem(STORAGE);if(raw){const x=JSON.parse(raw);x.bag&&setBag(x.bag);x.course&&setCourse(x.course);x.tee&&setTee(x.tee);x.scores&&setScores(x.scores);x.putts&&setPutts(x.putts);x.notes&&setNotes(x.notes);x.courseInfo&&setCourseInfo(x.courseInfo);x.targets&&setTargets(x.targets);x.units&&setUnits(x.units);x.player&&setPlayer(x.player);x.email&&setEmail(x.email);x.handicap!==undefined&&setHandicap(x.handicap);x.practiceDistance&&setPracticeDistance(x.practiceDistance)}}catch(e){}})();Tts.setDefaultLanguage('en-AU').catch(()=>{});Voice.onSpeechStart=()=>setListening(true);Voice.onSpeechEnd=()=>setListening(false);Voice.onSpeechError=()=>{setListening(false);setHeard('Microphone did not hear that. Tap and try again.')};Voice.onSpeechResults=e=>{const t=e.value?.[0]||'';setHeard(t?`Heard: ${t}`:'Nothing heard');if(t){parseSpeech(t,{setDistance,setWind,setWindDir,setElev,setLie});setPendingSpeak(true)}};return()=>{Voice.destroy().then(Voice.removeAllListeners).catch(()=>{})}},[]);
 useEffect(()=>{if(!pendingSpeak)return;const timer=setTimeout(()=>{Promise.resolve(Tts.stop()).catch(()=>{});Tts.speak(caddieText);setPendingSpeak(false)},220);return()=>clearTimeout(timer)},[caddieText,pendingSpeak]);
 useEffect(()=>{AsyncStorage.setItem(STORAGE,JSON.stringify({bag,course,tee,scores,putts,notes,courseInfo,targets,units,player,email,handicap,practiceDistance})).catch(()=>{})},[bag,course,tee,scores,putts,notes,courseInfo,targets,units,player,email,handicap,practiceDistance]);
 const ask=async()=>{try{if(Platform.OS==='android'){const ok=await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.RECORD_AUDIO);if(ok!==PermissionsAndroid.RESULTS.GRANTED){Alert.alert('Microphone permission','Allow microphone access so CaddieOS can hear you.');return}}if(listening){await Voice.stop();setListening(false)}else{setHeard('Listening…');await Voice.start('en-AU')}}catch(e){setListening(false);Alert.alert('Microphone','Unable to start speech recognition.')}};
 const getGPS=async()=>{try{if(Platform.OS==='android'){const ok=await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION);if(ok!==PermissionsAndroid.RESULTS.GRANTED){Alert.alert('Location permission','Allow location access so CaddieOS can use GPS.');return}}Geolocation.getCurrentPosition(p=>setGps({lat:p.coords.latitude.toFixed(6),lon:p.coords.longitude.toFixed(6),acc:Math.round(p.coords.accuracy)}),()=>Alert.alert('GPS','Could not get your current position.'),{enableHighAccuracy:true,timeout:15000,maximumAge:3000})}catch(e){Alert.alert('GPS','Unable to start location services.')}};
 const markTarget=kind=>{if(!gps){Alert.alert('Mark target','Get your GPS position first, then mark the target.');return}const idx=Math.min(17,Math.max(0,n(hole)-1)),p={lat:Number(gps.lat),lon:Number(gps.lon)};setTargets(prev=>prev.map((x,i)=>i===idx?{...x,[kind]:p}:x));Alert.alert('Saved',`${kind.toUpperCase()} saved for hole ${idx+1}.`)};
 const go=x=>{setScreen(null);setTab(x)},open=x=>setScreen(x),page=screen||tab;
 if(!entered)return <SafeAreaView style={s.loginSafe}><StatusBar barStyle="light-content" backgroundColor={C.dark}/><Welcome player={player} setPlayer={setPlayer} email={email} setEmail={setEmail} enter={()=>setEntered(true)} ui={ui}/></SafeAreaView>;
 return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor={C.bg}/><Header go={()=>go('HOME')} ui={ui}/><View style={s.flex}><ScrollView style={s.flex} contentContainerStyle={[s.body,compact&&s.bodyCompact]} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
 {page==='HOME'&&<Home go={go} open={open} course={course} hole={hole} player={player} played={played} total={total} toPar={toPar}/>} 
 {page==='ROUND'&&<Round go={go} result={result} hole={hole} gps={gps} getGPS={getGPS} targetDistances={targetDistances} units={units}/>} 
 {page==='CADDIE'&&<Caddie result={result} distance={distance} setDistance={setDistance} wind={wind} setWind={setWind} windDir={windDir} setWindDir={setWindDir} elev={elev} setElev={setElev} lie={lie} setLie={setLie} hole={hole} ask={ask} listening={listening} heard={heard} caddieText={caddieText} note={notes[n(hole)-1]||''} setNote={v=>setNotes(notes.map((x,i)=>i===n(hole)-1?v:x))} units={units}/>} 
 {page==='BAG'&&<Bag bag={bag} setBag={setBag} units={units}/>} 
 {page==='COURSE'&&<Course course={course} setCourse={setCourse} tee={tee} setTee={setTee} hole={hole} setHole={setHole} gps={gps} getGPS={getGPS} open={open} markTarget={markTarget} currentTarget={currentTarget}/>} 
 {page==='MORE'&&<More open={open} units={units} handicap={handicap}/>} 
 {page==='SCORE'&&<Score scores={scores} setScores={setScores} putts={putts} setPutts={setPutts} total={total} toPar={toPar} played={played}/>} 
 {page==='PRACTICE'&&<Practice practice={practice} setPractice={setPractice} shape={shape} setShape={setShape} shotResult={shotResult} setShotResult={setShotResult} practiceDistance={practiceDistance} setPracticeDistance={setPracticeDistance}/>} 
 {page==='WARMUP'&&<Checklist kicker="PRE-ROUND" title="Warm-Up" items={WARM} done={warmDone} setDone={setWarmDone}/>} 
 {page==='ROUTINES'&&<Checklist kicker="MENTAL GAME" title="Routines" items={ROUTINES} done={routineDone} setDone={setRoutineDone}/>} 
 {page==='SETTINGS'&&<Settings units={units} setUnits={setUnits} player={player} setPlayer={setPlayer} email={email} setEmail={setEmail} setCaddieName={setCaddieName} handicap={handicap} setHandicap={setHandicap} logout={()=>setEntered(false)}/>} 
 {page==='SUMMARY'&&<Summary course={course} tee={tee} scores={scores} putts={putts} notes={notes} total={total} totalPutts={totalPutts} played={played} toPar={toPar}/>} 
 {page==='COURSEINFO'&&<CourseInfo course={course} info={courseInfo} setInfo={setCourseInfo}/>} 
 </ScrollView></View><BottomNav tab={tab} go={go} ui={ui}/></SafeAreaView>;
}

function BrandMark({large=false}){return <View style={[s.brandMark,large&&s.brandMarkLarge]}><Text style={[s.crown,large&&s.crownLarge]}>♛</Text><View style={[s.ball,large&&s.ballLarge]}><Text style={[s.ballC,large&&s.ballCLarge]}>C</Text><Text style={[s.ballFlag,large&&s.ballFlagLarge]}>⚑</Text></View><View style={[s.orbit,large&&s.orbitLarge]}/></View>}
function Welcome({player,setPlayer,email,setEmail,enter,ui}){return <ScrollView style={s.loginScroll} contentContainerStyle={[s.loginWrap,ui.compact&&s.loginWrapCompact]} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View style={[s.loginSky,ui.compact&&s.loginSkyCompact]}><BrandMark large/><Text style={[s.loginBrand,ui.compact&&s.loginBrandCompact]}>Caddie<Text style={s.loginBlue}>OS</Text></Text><Text style={s.loginTag}>YOUR CADDIE • YOUR GAME</Text><Text style={[s.loginRule,ui.compact&&s.loginRuleCompact]}>PLAY  •  PRACTICE  •  IMPROVE</Text></View><View style={[s.loginPanel,ui.compact&&s.loginPanelCompact]}><Text style={[s.loginWelcome,ui.compact&&s.loginWelcomeCompact]}>WELCOME TO CADDIEOS</Text><Text style={[s.loginSub,ui.compact&&s.loginSubCompact]}>LET'S PLAY BETTER GOLF</Text><TextInput style={[s.loginInput,ui.compact&&s.loginInputCompact]} value={player} onChangeText={setPlayer} placeholder="Your Name (e.g. Dale)" placeholderTextColor="#A9B0B6"/><TextInput style={[s.loginInput,ui.compact&&s.loginInputCompact]} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email (optional)" placeholderTextColor="#A9B0B6"/><TouchableOpacity style={[s.loginButton,ui.compact&&s.loginButtonCompact]} onPress={enter}><Text style={[s.loginButtonText,ui.compact&&s.loginButtonTextCompact]}>ENTER CADDIEOS</Text><Text style={s.loginArrow}>›</Text></TouchableOpacity><Text style={[s.loginMotto,ui.compact&&s.loginMottoCompact]}>Smarter decisions. Better scores. More fun.</Text><Text style={[s.loginScript,ui.compact&&s.loginScriptCompact]}>Golf is a game for life</Text></View></ScrollView>}
function Header({go,ui}){return <View style={[s.header,ui.compact&&s.headerCompact]}><TouchableOpacity onPress={go} style={s.headerBrand}><BrandMark/><View><Text style={[s.brand,ui.compact&&s.brandCompact]}>Caddie<Text style={s.blue}>OS</Text></Text><Text style={s.tag}>YOUR CADDIE • YOUR GAME</Text></View></TouchableOpacity><Text style={s.headerGold}>ANTI-GLARE</Text></View>}
function BottomNav({tab,go,ui}){return <View style={[s.bottomNav,ui.compact&&s.bottomNavCompact]}>{NAV.map(x=><TouchableOpacity key={x} onPress={()=>go(x)} style={s.navItem}><Text style={[s.navGlyph,tab===x&&s.navGlyphOn]}>{x==='HOME'?'⌂':x==='CADDIE'?'♟':x==='BAG'?'▣':x==='COURSE'?'⌖':'≡'}</Text><Text style={[s.navText,tab===x&&s.navTextOn]}>{x[0]+x.slice(1).toLowerCase()}</Text></TouchableOpacity>)}</View>}
function PageHead({kicker,title,badge}){return <View style={s.pageHead}><View style={s.flex}><Text style={s.kicker}>{kicker}</Text><Text style={s.pageTitle}>{title}</Text></View>{badge?<View style={s.pill}><Text style={s.pillText}>{badge}</Text></View>:null}</View>}
function Tile({title,sub,icon,onPress}){return <TouchableOpacity onPress={onPress} style={s.tile}><Text style={s.tileIcon}>{icon}</Text><Text style={s.tileTitle}>{title}</Text><Text style={s.tileSub}>{sub}</Text></TouchableOpacity>}
function Chip({label,on,press}){return <TouchableOpacity onPress={press} style={[s.chip,on&&s.chipOn]}><Text style={[s.chipText,on&&s.chipTextOn]}>{label}</Text></TouchableOpacity>}
function Field({label,value,setValue,suffix}){return <View style={s.field}><Text style={s.fieldLabel}>{label}</Text><View style={s.fieldInner}><TextInput style={s.fieldInput} value={String(value)} onChangeText={setValue} keyboardType="numeric"/><Text style={s.fieldSuffix}>{suffix}</Text></View></View>}
function Home({go,open,course,hole,player,played,total,toPar}){const tiles=[['PRACTICE','Wedges to putting','⚑','PRACTICE'],['WARM-UP','8-step preparation','♨','WARMUP'],['SCORECARD',played?`${played} holes • ${total}`:'18-hole card','▤','SCORE'],['COURSE','Setup & mapping','⌖','COURSE'],['ROUTINES','8-step mental game','☷','ROUTINES'],['SETTINGS','Player & units','⚙','SETTINGS']];return <><View style={s.homeWelcome}><Text style={s.homeSmall}>GOOD TO SEE YOU</Text><Text style={s.homeName}>{player||'Player'}</Text><Text style={s.homeMeta}>{course?`${course} • Hole ${hole}`:'Course not selected'}</Text></View><TouchableOpacity style={s.homeStart} onPress={()=>open('ROUND')}><View style={s.homeStartBall}><Text style={s.homeStartBallText}>●</Text></View><View style={s.flex}><Text style={s.homeStartTitle}>START ROUND</Text><Text style={s.homeStartSub}>{played?`${toPar>0?'+':''}${toPar} • ${played} holes recorded`:'GPS • Caddie • Scoring'}</Text></View><Text style={s.homeArrow}>›</Text></TouchableOpacity><View style={s.grid}>{tiles.map(([a,b,i,c])=><Tile key={a} title={a} sub={b} icon={i} onPress={()=>c==='COURSE'?go('COURSE'):open(c)}/>)}</View><TouchableOpacity style={s.roundSummaryBar} onPress={()=>open('SUMMARY')}><Text style={s.roundSummaryTitle}>ROUND SUMMARY</Text><Text style={s.roundSummarySub}>{played?`${total} shots • ${played}/18`:'Ready after your first hole'}</Text><Text style={s.roundSummaryArrow}>›</Text></TouchableOpacity></>}
function HoleMap({gps,distances,units}){const u=units==='METRES'?'m':'yd';return <View style={s.mapCard}><View style={s.mapTop}><View><Text style={s.fieldLabelLight}>HOLE MAP / GPS</Text><Text style={s.mapStatus}>{gps?'GPS ON':'GPS NOT SET'}</Text></View><Text style={s.mapFlag}>⚑</Text></View><View style={s.mapVisual}><View style={s.green}><Text style={s.greenText}>GREEN</Text></View><View style={s.fairwayLine}/><View style={s.playerDot}/></View><View style={s.distanceStrip}>{[['FRONT',distances.front],['CENTRE',distances.center],['BACK',distances.back]].map(([l,v])=><View key={l} style={s.distanceMini}><Text style={s.distanceMiniLabel}>{l}</Text><Text style={s.distanceMiniValue}>{v==null?'—':`${v} ${u}`}</Text></View>)}</View></View>}
function Round({go,result,hole,gps,getGPS,targetDistances,units}){const du=units==='METRES'?'m':'yd';return <><PageHead kicker="ROUND" title={`Hole ${hole}`} badge="LIVE"/><HoleMap gps={gps} distances={targetDistances} units={units}/>{!gps&&<TouchableOpacity style={s.goldOutline} onPress={getGPS}><Text style={s.goldOutlineText}>GET GPS POSITION</Text></TouchableOpacity>}<View style={s.roundMetrics}><View style={s.roundMetric}><Text style={s.metricLabel}>DISTANCE TO PIN</Text><Text style={s.metricBig}>{targetDistances.center==null?'—':targetDistances.center}<Text style={s.metricUnit}> {du}</Text></Text></View><View style={s.roundMetric}><Text style={s.metricLabel}>PLAYS LIKE</Text><Text style={s.metricBig}>{result.y}<Text style={s.metricUnit}> {du}</Text></Text></View></View><View style={s.recommend}><Text style={s.metricLabel}>RECOMMENDED CLUB</Text><Text style={s.recommendClub}>{result.club}</Text><Text style={s.recommendSub}>Stock carry {result.carry} {du}</Text></View><TouchableOpacity style={s.goldButton} onPress={()=>go('CADDIE')}><Text style={s.goldButtonText}>ASK CADDIE</Text><Text style={s.goldButtonArrow}>›</Text></TouchableOpacity></>}
function Caddie({result,distance,setDistance,wind,setWind,windDir,setWindDir,elev,setElev,lie,setLie,hole,ask,listening,heard,caddieText,note,setNote,units}){const du=units==='METRES'?'m':'yd',wu=units==='METRES'?'km/h':'mph';return <><PageHead kicker="CADDIE" title={`Hole ${hole}`} badge="AI CADDIE"/><TouchableOpacity style={[s.micHero,listening&&s.micHeroLive]} onPress={ask}><View style={s.micRing}><Text style={s.micSymbol}>●</Text></View><Text style={s.micHeroTitle}>{listening?'LISTENING…':'CADDIE'}</Text><Text style={s.micHeroSub}>{listening?'Speak now':'Distance, lie, wind, trouble or club'}</Text></TouchableOpacity><View style={s.heardBox}><Text style={s.heardLabel}>HEARD</Text><Text style={s.heardText}>{heard}</Text></View><View style={s.answerBox}><Text style={s.answerLabel}>CADDIE SAYS</Text><Text style={s.answerText}>{caddieText}</Text></View><View style={s.quickGrid}><View style={s.quickCard}><Text style={s.quickLabel}>PLAYS LIKE</Text><Text style={s.quickValue}>{result.y} {du}</Text></View><View style={s.quickCard}><Text style={s.quickLabel}>CLUB</Text><Text style={s.quickValue}>{result.club}</Text></View><View style={s.quickCard}><Text style={s.quickLabel}>WIND</Text><Text style={s.quickValue}>{wind||0} {wu}</Text></View><View style={s.quickCard}><Text style={s.quickLabel}>LIE</Text><Text style={s.quickValueSmall}>{lie}</Text></View></View><View style={s.card}><View style={s.row}><Field label="TARGET" value={distance} setValue={setDistance} suffix={du}/><Field label="WIND" value={wind} setValue={setWind} suffix={wu}/><Field label="SLOPE" value={elev} setValue={setElev} suffix="%"/></View><Text style={s.sectionLabel}>WIND DIRECTION</Text><View style={s.chipRow}>{WIND_DIRS.map(x=><Chip key={x} label={x} on={windDir===x} press={()=>setWindDir(x)}/>)}</View><Text style={s.helper}>{windGuide(wind,windDir,units)}</Text><Text style={s.sectionLabel}>LIE</Text><View style={s.chipRow}>{LIES.map(x=><Chip key={x} label={x} on={lie===x} press={()=>setLie(x)}/>)}</View><Text style={s.sectionLabel}>CADDIE NOTE</Text><TextInput style={[s.input,s.note]} value={note} onChangeText={setNote} multiline placeholder="Shot plan, trouble, reminder…" placeholderTextColor={C.muted}/></View></>}
function Bag({bag,setBag,units}){const change=(i,d)=>setBag(p=>p.map((x,j)=>j===i?[x[0],x[0]==='Putter'?0:Math.max(0,x[1]+d)]:x)),u=units==='METRES'?'m':'yd';return <><PageHead kicker="MY BAG" title="14 Clubs" badge={units}/><View style={s.bagPanel}>{bag.map(([name,m],i)=><View key={name} style={s.bagRow}><Text style={s.bagName}>{name}</Text><View style={s.bagEdit}><TouchableOpacity onPress={()=>change(i,-1)} style={s.bagStep}><Text style={s.bagStepText}>−</Text></TouchableOpacity><Text style={s.bagDist}>{carryForUnits(m,units)} <Text style={s.bagUnit}>{u}</Text></Text><TouchableOpacity onPress={()=>change(i,1)} style={s.bagStep}><Text style={s.bagStepText}>+</Text></TouchableOpacity></View></View>)}</View></>}
function Course({course,setCourse,tee,setTee,hole,setHole,gps,getGPS,open,markTarget,currentTarget}){return <><PageHead kicker="COURSE" title={course||'Course Setup'} badge={`HOLE ${hole}`}/><View style={s.card}><Text style={s.sectionLabel}>COURSE NAME</Text><TextInput style={s.input} value={course} onChangeText={setCourse} placeholder="Search or enter course name" placeholderTextColor={C.muted}/><Text style={s.sectionLabel}>TEE COLOUR</Text><View style={s.chipRow}>{TEES.map(x=><Chip key={x} label={x} on={tee===x} press={()=>setTee(x)}/>)}</View><Text style={s.sectionLabel}>HOLE</Text><View style={s.holeGrid}>{Array.from({length:18},(_,i)=>String(i+1)).map(x=><TouchableOpacity key={x} style={[s.holeBtn,hole===x&&s.holeBtnOn]} onPress={()=>setHole(x)}><Text style={[s.holeBtnText,hole===x&&s.holeBtnTextOn]}>{x}</Text></TouchableOpacity>)}</View></View><View style={s.card}><Text style={s.sectionLabelTop}>GPS COURSE MAPPER</Text><TouchableOpacity style={s.goldOutline} onPress={getGPS}><Text style={s.goldOutlineText}>{gps?'REFRESH GPS':'GET GPS POSITION'}</Text></TouchableOpacity>{gps&&<Text style={s.helper}>GPS {gps.lat}, {gps.lon} • ±{gps.acc}m</Text>}<View style={s.markRow}>{['front','center','back'].map(k=><TouchableOpacity key={k} style={[s.markBtn,currentTarget[k]&&s.markDone]} onPress={()=>markTarget(k)}><Text style={s.markText}>{currentTarget[k]?'✓ ':''}{k.toUpperCase()}</Text></TouchableOpacity>)}</View></View><TouchableOpacity style={s.goldButton} onPress={()=>open('COURSEINFO')}><Text style={s.goldButtonText}>COURSE INFORMATION</Text><Text style={s.goldButtonArrow}>›</Text></TouchableOpacity></>}
function More({open,units,handicap}){const rows=[['Warm-Up','WARMUP','♨'],['Routines','ROUTINES','☷'],['Round Summary','SUMMARY','▤'],['Settings','SETTINGS','⚙']];return <><PageHead kicker="CADDIEOS" title="More"/><View style={s.menuPanel}>{rows.map(([a,b,i])=><TouchableOpacity key={a} style={s.menuRow} onPress={()=>open(b)}><Text style={s.menuIcon}>{i}</Text><Text style={s.menuTitle}>{a}</Text><Text style={s.menuArrow}>›</Text></TouchableOpacity>)}<View style={s.menuInfo}><Text style={s.menuInfoKey}>UNITS</Text><Text style={s.menuInfoVal}>{units}</Text></View><View style={s.menuInfo}><Text style={s.menuInfoKey}>HANDICAP</Text><Text style={s.menuInfoVal}>{handicap||'—'}</Text></View></View></>}
function ScoreCell({value,onChange}){return <TextInput style={s.scoreInput} value={String(value)} onChangeText={onChange} keyboardType="number-pad" maxLength={2} selectTextOnFocus/>}
function ScoreNine({start,scores,setScores,putts,setPutts}){const ids=Array.from({length:9},(_,i)=>start+i);return <View style={s.scoreHalf}><View style={s.scoreHeader}><Text style={[s.scoreH,s.scoreHole]}>H</Text><Text style={s.scoreH}>PAR</Text><Text style={s.scoreH}>S</Text><Text style={s.scoreH}>P</Text></View>{ids.map(i=><View key={i} style={s.scoreLine}><Text style={[s.scoreN,s.scoreHole]}>{i+1}</Text><Text style={s.scorePar}>{PARS[i]}</Text><ScoreCell value={scores[i]} onChange={v=>setScores(scores.map((x,j)=>j===i?v.replace(/[^0-9]/g,''):x))}/><ScoreCell value={putts[i]} onChange={v=>setPutts(putts.map((x,j)=>j===i?v.replace(/[^0-9]/g,''):x))}/></View>)}<View style={s.scoreTotalLine}><Text style={[s.scoreN,s.scoreHole]}>{start===0?'OUT':'IN'}</Text><Text style={s.scorePar}>{PARS.slice(start,start+9).reduce((a,b)=>a+b,0)}</Text><Text style={s.scoreSum}>{scores.slice(start,start+9).reduce((a,b)=>a+n(b),0)||'—'}</Text><Text style={s.scoreSum}>{putts.slice(start,start+9).reduce((a,b)=>a+n(b),0)||'—'}</Text></View></View>}
function Score({scores,setScores,putts,setPutts,total,toPar,played}){return <><PageHead kicker="GAME REPORT" title="Scorecard" badge={`${played}/18`}/><View style={s.scoreBoard}><ScoreNine start={0} scores={scores} setScores={setScores} putts={putts} setPutts={setPutts}/><View style={s.scoreDivider}/><ScoreNine start={9} scores={scores} setScores={setScores} putts={putts} setPutts={setPutts}/></View><View style={s.scoreFooter}><Text style={s.scoreFooterText}>PAR 72</Text><Text style={s.scoreFooterText}>SCORE {total||'—'}</Text><Text style={s.scoreFooterText}>TO PAR {played?(toPar>0?`+${toPar}`:String(toPar)):'—'}</Text></View></>}
function Practice({practice,setPractice,shape,setShape,shotResult,setShotResult,practiceDistance,setPracticeDistance}){const bump=d=>setPracticeDistance(String(Math.max(0,n(practiceDistance)+d)));return <><PageHead kicker="PRACTICE" title="Practice"/><View style={s.card}><Text style={s.sectionLabelTop}>AREA</Text><View style={s.chipRow}>{PRACTICE.map(x=><Chip key={x} label={x} on={practice===x} press={()=>setPractice(x)}/>)}</View><View style={s.practiceDistance}><TouchableOpacity style={s.practiceStep} onPress={()=>bump(-5)}><Text style={s.practiceStepText}>−</Text></TouchableOpacity><View><Text style={s.practiceLabel}>TARGET</Text><Text style={s.practiceBig}>{practiceDistance} m</Text></View><TouchableOpacity style={s.practiceStep} onPress={()=>bump(5)}><Text style={s.practiceStepText}>+</Text></TouchableOpacity></View><Text style={s.sectionLabel}>SHOT SHAPE</Text><View style={s.chipRow}>{['Straight','Draw','Fade'].map(x=><Chip key={x} label={x} on={shape===x} press={()=>setShape(x)}/>)}</View><Text style={s.sectionLabel}>RESULT</Text><View style={s.chipRow}>{['Good','Left','Right','Short','Long'].map(x=><Chip key={x} label={x} on={shotResult===x} press={()=>setShotResult(x)}/>)}</View><TouchableOpacity style={s.goldButton}><Text style={s.goldButtonText}>SAVE SHOT</Text></TouchableOpacity></View></>}
function Checklist({kicker,title,items,done,setDone}){const toggle=x=>setDone(done.includes(x)?done.filter(v=>v!==x):[...done,x]);return <><PageHead kicker={kicker} title={title} badge={`${done.length}/${items.length}`}/><View style={s.menuPanel}>{items.map((x,i)=><TouchableOpacity key={x} style={s.checkRow} onPress={()=>toggle(x)}><View style={[s.checkBox,done.includes(x)&&s.checkOn]}><Text style={s.checkMark}>{done.includes(x)?'✓':i+1}</Text></View><Text style={s.checkText}>{x}</Text></TouchableOpacity>)}</View></>}
function Settings({units,setUnits,player,setPlayer,email,setEmail,handicap,setHandicap,logout}){return <><PageHead kicker="CADDIEOS" title="Settings"/><View style={s.card}><Text style={s.sectionLabelTop}>PLAYER</Text><TextInput style={s.input} value={player} onChangeText={setPlayer}/><Text style={s.sectionLabel}>EMAIL</Text><TextInput style={s.input} value={email} onChangeText={setEmail} autoCapitalize="none"/><Text style={s.sectionLabel}>HANDICAP</Text><TextInput style={s.input} value={handicap} onChangeText={setHandicap} keyboardType="numeric" placeholder="Optional" placeholderTextColor={C.muted}/><Text style={s.sectionLabel}>UNITS</Text><View style={s.chipRow}>{['METRES','YARDS'].map(x=><Chip key={x} label={x} on={units===x} press={()=>setUnits(x)}/>)}</View><TouchableOpacity style={s.goldOutline} onPress={logout}><Text style={s.goldOutlineText}>SIGN OUT</Text></TouchableOpacity></View></>}
function Summary({course,tee,scores,putts,notes,total,totalPutts,played,toPar}){return <><PageHead kicker="ROUND" title="Round Summary" badge={`${played}/18`}/><View style={s.summaryHero}><Text style={s.summaryScore}>{total||'—'}</Text><Text style={s.summaryMeta}>{course||'Course'} • {tee} tee</Text><Text style={s.summaryMeta}>{totalPutts} putts • {played?(toPar>0?`+${toPar}`:toPar):'—'} to par</Text></View>{scores.map((v,i)=>v||notes[i]?<View key={i} style={s.summaryRow}><Text style={s.summaryHole}>{i+1}</Text><Text style={s.summaryText}>Par {PARS[i]} • Score {v||'—'} • Putts {putts[i]||'—'}{notes[i]?` • ${notes[i]}`:''}</Text></View>:null)}</>}
function CourseInfo({course,info,setInfo}){const set=(k,v)=>setInfo({...info,[k]:v});return <><PageHead kicker="COURSE INFO" title={course||'Course Information'}/><View style={s.courseBanner}><Text style={s.courseBannerFlag}>⚑</Text><Text style={s.courseBannerText}>{course||'Your Course'}</Text></View><View style={s.card}>{[['phone','PHONE'],['email','EMAIL'],['membership','MEMBERSHIP'],['pro','GOLF PRO']].map(([k,l])=><View key={k}><Text style={s.sectionLabel}>{l}</Text><TextInput style={s.input} value={info[k]} onChangeText={v=>set(k,v)}/></View>)}<Text style={s.sectionLabel}>FACILITIES</Text>{[['cart','CARTS'],['hire','CLUB HIRE'],['proshop','PRO SHOP']].map(([k,l])=><View key={k} style={s.facilityRow}><Text style={s.facilityText}>{l}</Text><View style={s.chipRow}><Chip label="YES" on={info[k]==='Yes'} press={()=>set(k,'Yes')}/><Chip label="NO" on={info[k]==='No'} press={()=>set(k,'No')}/></View></View>)}</View></>}

const s=StyleSheet.create({
 loginSafe:{flex:1,backgroundColor:C.dark},safe:{flex:1,backgroundColor:C.bg,paddingTop:Platform.OS==='android'?(StatusBar.currentHeight||24):0,paddingBottom:Platform.OS==='android'?34:0},flex:{flex:1},body:{paddingHorizontal:12,paddingTop:10,paddingBottom:16},bodyCompact:{paddingHorizontal:9,paddingTop:5,paddingBottom:8},
 loginScroll:{flex:1,backgroundColor:C.dark},loginWrap:{flexGrow:1,minHeight:'100%',backgroundColor:C.dark},loginWrapCompact:{paddingBottom:8},loginSky:{flexGrow:1,flexShrink:1,minHeight:260,alignItems:'center',justifyContent:'center',paddingTop:16,paddingBottom:12,paddingHorizontal:20,backgroundColor:C.bg2},loginSkyCompact:{minHeight:230,paddingTop:10,paddingBottom:8},loginPanel:{flexGrow:1,flexShrink:0,paddingHorizontal:20,paddingTop:16,paddingBottom:18,backgroundColor:C.dark},loginPanelCompact:{paddingHorizontal:16,paddingTop:12,paddingBottom:12},loginBrand:{fontSize:46,fontWeight:'900',color:C.gold2,marginTop:10},loginBrandCompact:{fontSize:40,marginTop:5},loginBlue:{color:'#159FE4'},loginTag:{fontSize:11,fontWeight:'900',letterSpacing:2.5,color:C.white,marginTop:1},loginRule:{fontSize:11,fontWeight:'800',letterSpacing:3,color:C.gold2,marginTop:16},loginRuleCompact:{marginTop:10,fontSize:10,letterSpacing:2.4},loginWelcome:{fontSize:25,fontWeight:'900',textAlign:'center',color:C.gold2,letterSpacing:1},loginWelcomeCompact:{fontSize:22},loginSub:{fontSize:12,fontWeight:'800',textAlign:'center',color:C.white,letterSpacing:3,marginTop:4,marginBottom:15},loginSubCompact:{fontSize:11,marginBottom:11},loginInput:{height:50,borderWidth:1.5,borderColor:C.gold,borderRadius:14,backgroundColor:'#0B2C43',paddingHorizontal:16,color:C.white,fontSize:15,marginBottom:10},loginInputCompact:{height:46,marginBottom:8},loginButton:{height:54,borderRadius:27,backgroundColor:C.gold2,borderWidth:1,borderColor:'#FFE29A',flexDirection:'row',alignItems:'center',justifyContent:'center',marginTop:1},loginButtonCompact:{height:50,borderRadius:25},loginButtonText:{fontSize:18,fontWeight:'900',color:C.dark},loginButtonTextCompact:{fontSize:16},loginArrow:{position:'absolute',right:20,fontSize:35,fontWeight:'500',color:C.dark},loginMotto:{fontSize:12,fontStyle:'italic',textAlign:'center',color:'#D9DDE0',letterSpacing:1.4,marginTop:14},loginMottoCompact:{fontSize:11,marginTop:10},loginScript:{fontSize:25,fontStyle:'italic',textAlign:'center',color:C.gold2,marginTop:15,marginBottom:8},loginScriptCompact:{fontSize:21,marginTop:10,marginBottom:4},
 brandMark:{width:42,height:42,alignItems:'center',justifyContent:'center',marginRight:8},brandMarkLarge:{width:118,height:118,marginRight:0},crown:{position:'absolute',top:-1,fontSize:17,color:C.gold2,zIndex:4},crownLarge:{fontSize:40,top:-5},ball:{width:31,height:31,borderRadius:16,backgroundColor:C.white,borderWidth:2,borderColor:C.gold,alignItems:'center',justifyContent:'center'},ballLarge:{width:86,height:86,borderRadius:43,borderWidth:4},ballC:{fontSize:19,fontWeight:'900',color:C.gold},ballCLarge:{fontSize:50},ballFlag:{position:'absolute',right:4,top:3,fontSize:9,color:C.gold},ballFlagLarge:{right:10,top:9,fontSize:20},orbit:{position:'absolute',width:41,height:20,borderWidth:2,borderColor:C.gold,borderRadius:20,transform:[{rotate:'-15deg'}]},orbitLarge:{width:116,height:52,borderWidth:4,borderRadius:58},
 header:{height:72,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:12,borderBottomWidth:1,borderBottomColor:'#234359',backgroundColor:C.bg},headerCompact:{height:56,paddingHorizontal:9},headerBrand:{flexDirection:'row',alignItems:'center',flexShrink:1,minWidth:0},brand:{fontSize:25,fontWeight:'900',color:C.gold2},brandCompact:{fontSize:23},blue:{color:'#149EE2'},tag:{fontSize:8,fontWeight:'800',letterSpacing:1.8,color:'#E4E8EB'},headerGold:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:C.gold2,marginLeft:6,flexShrink:0},
 bottomNav:{minHeight:66,flexDirection:'row',backgroundColor:C.dark,borderTopWidth:1,borderTopColor:'#234359',paddingTop:5,paddingBottom:6},bottomNavCompact:{minHeight:64,paddingTop:4,paddingBottom:5},navItem:{flex:1,alignItems:'center',justifyContent:'center'},navGlyph:{fontSize:20,color:'#8997A1'},navGlyphOn:{color:C.gold2},navText:{fontSize:9,fontWeight:'800',color:'#8997A1',marginTop:2},navTextOn:{color:C.gold2},
 pageHead:{flexDirection:'row',alignItems:'center',marginBottom:9},kicker:{fontSize:10,fontWeight:'900',letterSpacing:2,color:C.gold2},pageTitle:{fontSize:26,fontWeight:'900',color:C.white},pill:{backgroundColor:C.gold2,borderRadius:18,paddingHorizontal:11,paddingVertical:6},pillText:{color:C.dark,fontWeight:'900',fontSize:10},
 homeWelcome:{alignItems:'center',marginBottom:5},homeSmall:{fontSize:11,fontWeight:'800',letterSpacing:2,color:'#C9D2D8'},homeName:{fontSize:28,fontWeight:'900',color:C.white},homeMeta:{fontSize:11,color:'#A9B6BF',marginTop:2},homeStart:{flexDirection:'row',alignItems:'center',backgroundColor:'#0D4B78',borderWidth:1,borderColor:C.gold,borderRadius:14,padding:10,marginBottom:6},homeStartBall:{width:38,height:38,borderRadius:19,backgroundColor:C.white,alignItems:'center',justifyContent:'center',marginRight:10},homeStartBallText:{fontSize:19,color:'#C6C9CB'},homeStartTitle:{fontSize:18,fontWeight:'900',color:C.white},homeStartSub:{fontSize:10,color:'#D5E5EF',marginTop:2},homeArrow:{fontSize:34,color:C.gold2},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',rowGap:6},tile:{width:'48.7%',minHeight:78,backgroundColor:C.panel,borderWidth:1,borderColor:C.gold,borderRadius:12,padding:7,alignItems:'center',justifyContent:'center'},tileIcon:{fontSize:21,color:C.navy,marginBottom:2},tileTitle:{fontSize:13,fontWeight:'900',color:C.navy},tileSub:{fontSize:9,color:C.muted,fontWeight:'700',marginTop:2,textAlign:'center'},roundSummaryBar:{marginTop:6,backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:12,padding:8},roundSummaryTitle:{fontSize:12,fontWeight:'900',color:C.navy},roundSummarySub:{fontSize:10,color:C.muted,marginTop:2},roundSummaryArrow:{position:'absolute',right:12,top:12,fontSize:28,color:C.gold},
 card:{backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:14,padding:11,marginBottom:9},sectionLabelTop:{fontSize:10,fontWeight:'900',letterSpacing:1.3,color:C.muted,marginBottom:5},sectionLabel:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:C.muted,marginTop:9,marginBottom:5},input:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:9,minHeight:42,paddingHorizontal:10,paddingVertical:8,fontSize:14,color:C.text},note:{minHeight:60,textAlignVertical:'top'},helper:{fontSize:11,color:C.text,fontWeight:'600',marginTop:6},
 mapCard:{backgroundColor:C.panel,borderWidth:1,borderColor:C.gold,borderRadius:14,padding:9,marginBottom:8},mapTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},fieldLabelLight:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:C.muted},mapStatus:{fontSize:14,fontWeight:'900',color:C.navy,marginTop:1},mapFlag:{fontSize:28,color:C.gold},mapVisual:{height:116,backgroundColor:'#6F9258',borderRadius:10,alignItems:'center',justifyContent:'flex-start',marginTop:7,overflow:'hidden'},green:{width:'42%',height:30,backgroundColor:'#AFCB96',borderRadius:18,alignItems:'center',justifyContent:'center',marginTop:6},greenText:{fontSize:9,fontWeight:'900',color:C.navy},fairwayLine:{width:5,height:58,backgroundColor:'#B7D09F'},playerDot:{width:15,height:15,borderRadius:8,backgroundColor:'#167ED0',borderWidth:2,borderColor:C.white},distanceStrip:{flexDirection:'row',gap:5,marginTop:6},distanceMini:{flex:1,backgroundColor:C.white,borderRadius:8,paddingVertical:6,alignItems:'center'},distanceMiniLabel:{fontSize:8,fontWeight:'900',color:C.muted},distanceMiniValue:{fontSize:14,fontWeight:'900',color:C.navy,marginTop:1},
 roundMetrics:{flexDirection:'row',gap:8,marginBottom:8},roundMetric:{flex:1,backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:12,padding:10},metricLabel:{fontSize:9,fontWeight:'900',letterSpacing:1,color:C.muted},metricBig:{fontSize:28,fontWeight:'900',color:C.navy,marginTop:2},metricUnit:{fontSize:14,color:C.muted},recommend:{backgroundColor:C.panel,borderWidth:1,borderColor:C.gold,borderRadius:12,padding:12,marginBottom:8},recommendClub:{fontSize:29,fontWeight:'900',color:C.navy},recommendSub:{fontSize:11,fontWeight:'700',color:C.muted},
 goldButton:{minHeight:48,borderRadius:12,backgroundColor:C.gold2,borderWidth:1,borderColor:'#FFE39C',alignItems:'center',justifyContent:'center',marginTop:8,marginBottom:8},goldButtonText:{fontSize:13,fontWeight:'900',color:C.dark},goldButtonArrow:{position:'absolute',right:14,fontSize:28,color:C.dark},goldOutline:{minHeight:42,borderRadius:11,borderWidth:1,borderColor:C.gold,alignItems:'center',justifyContent:'center',marginBottom:8},goldOutlineText:{fontSize:11,fontWeight:'900',color:C.gold2},
 micHero:{backgroundColor:C.bg2,borderWidth:1,borderColor:C.gold,borderRadius:15,alignItems:'center',padding:14,marginBottom:8},micHeroLive:{backgroundColor:'#123E5A'},micRing:{width:64,height:64,borderRadius:32,borderWidth:3,borderColor:C.gold2,alignItems:'center',justifyContent:'center',backgroundColor:C.dark},micSymbol:{fontSize:26,color:C.white},micHeroTitle:{fontSize:15,fontWeight:'900',color:C.white,marginTop:8},micHeroSub:{fontSize:10,color:'#B9C7D0',marginTop:2},heardBox:{backgroundColor:C.panel,borderRadius:12,padding:10,marginBottom:7},heardLabel:{fontSize:9,fontWeight:'900',color:C.muted,letterSpacing:1.3},heardText:{fontSize:13,fontWeight:'700',color:C.text,marginTop:3},answerBox:{backgroundColor:C.dark,borderWidth:1,borderColor:C.gold,borderRadius:12,padding:11,marginBottom:8},answerLabel:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:C.gold2},answerText:{fontSize:15,fontWeight:'800',color:C.white,lineHeight:20,marginTop:4},quickGrid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',rowGap:7,marginBottom:8},quickCard:{width:'48.8%',backgroundColor:C.panel,borderRadius:11,padding:9,borderWidth:1,borderColor:C.line},quickLabel:{fontSize:8,fontWeight:'900',letterSpacing:1,color:C.muted},quickValue:{fontSize:17,fontWeight:'900',color:C.navy,marginTop:2},quickValueSmall:{fontSize:14,fontWeight:'900',color:C.navy,marginTop:3},
 row:{flexDirection:'row',gap:6},field:{flex:1},fieldLabel:{fontSize:9,fontWeight:'900',letterSpacing:1,color:C.muted},fieldInner:{flexDirection:'row',alignItems:'center',backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:8,paddingHorizontal:7,height:39,marginTop:3},fieldInput:{flex:1,fontSize:16,fontWeight:'900',color:C.navy,padding:0},fieldSuffix:{fontSize:9,fontWeight:'900',color:C.muted},chipRow:{flexDirection:'row',flexWrap:'wrap',gap:5},chip:{borderWidth:1,borderColor:C.line,borderRadius:14,paddingHorizontal:9,paddingVertical:6,backgroundColor:C.white},chipOn:{backgroundColor:C.gold2,borderColor:C.gold},chipText:{fontSize:9,fontWeight:'900',color:C.navy},chipTextOn:{color:C.dark},
 bagPanel:{backgroundColor:C.panel,borderWidth:1,borderColor:C.gold,borderRadius:14,paddingHorizontal:10},bagRow:{minHeight:41,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#D8CFBC'},bagName:{flex:1,fontSize:13,fontWeight:'800',color:C.navy},bagEdit:{flexDirection:'row',alignItems:'center'},bagStep:{width:26,height:26,borderRadius:6,backgroundColor:C.navy,alignItems:'center',justifyContent:'center'},bagStepText:{fontSize:18,fontWeight:'900',color:C.white},bagDist:{width:82,textAlign:'center',fontSize:15,fontWeight:'900',color:C.navy},bagUnit:{fontSize:9,color:C.muted},
 holeGrid:{flexDirection:'row',flexWrap:'wrap',gap:5},holeBtn:{width:'14.2%',aspectRatio:1.35,borderWidth:1,borderColor:C.line,borderRadius:7,alignItems:'center',justifyContent:'center',backgroundColor:C.white},holeBtnOn:{backgroundColor:C.gold2,borderColor:C.gold},holeBtnText:{fontWeight:'900',color:C.navy},holeBtnTextOn:{color:C.dark},markRow:{flexDirection:'row',gap:6,marginTop:6},markBtn:{flex:1,borderWidth:1,borderColor:C.gold,borderRadius:9,paddingVertical:9,alignItems:'center'},markDone:{backgroundColor:C.success},markText:{fontSize:10,fontWeight:'900',color:C.navy},
 menuPanel:{backgroundColor:C.panel,borderWidth:1,borderColor:C.gold,borderRadius:14,overflow:'hidden'},menuRow:{minHeight:50,flexDirection:'row',alignItems:'center',paddingHorizontal:12,borderBottomWidth:1,borderBottomColor:'#D8CFBC'},menuIcon:{width:30,fontSize:18,color:C.navy},menuTitle:{flex:1,fontSize:14,fontWeight:'800',color:C.navy},menuArrow:{fontSize:25,color:C.gold},menuInfo:{minHeight:43,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:12,borderBottomWidth:1,borderBottomColor:'#D8CFBC'},menuInfoKey:{fontSize:10,fontWeight:'900',letterSpacing:1,color:C.muted},menuInfoVal:{fontSize:12,fontWeight:'900',color:C.navy},
 scoreBoard:{flexDirection:'row',backgroundColor:C.panel,borderWidth:1,borderColor:C.gold,borderRadius:12,padding:5},scoreHalf:{flex:1},scoreDivider:{width:1,backgroundColor:C.line,marginHorizontal:4},scoreHeader:{height:22,flexDirection:'row',alignItems:'center',backgroundColor:C.gold2,borderRadius:5,marginBottom:1},scoreLine:{height:31,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#DDD2BD'},scoreTotalLine:{height:31,flexDirection:'row',alignItems:'center',backgroundColor:C.panel2,marginTop:1,borderRadius:4},scoreH:{width:'23%',textAlign:'center',fontSize:8,fontWeight:'900',color:C.dark},scoreHole:{width:'31%'},scoreN:{width:'31%',textAlign:'center',fontSize:11,fontWeight:'900',color:C.navy},scorePar:{width:'23%',textAlign:'center',fontSize:10,fontWeight:'800',color:C.muted},scoreInput:{width:'23%',height:25,borderWidth:1,borderColor:C.line,borderRadius:5,backgroundColor:C.white,textAlign:'center',fontSize:12,fontWeight:'900',color:C.navy,padding:0},scoreSum:{width:'23%',textAlign:'center',fontSize:10,fontWeight:'900',color:C.navy},scoreFooter:{flexDirection:'row',justifyContent:'space-between',backgroundColor:C.dark,borderWidth:1,borderColor:C.gold,borderRadius:10,paddingHorizontal:10,paddingVertical:8,marginTop:7},scoreFooterText:{fontSize:10,fontWeight:'900',color:C.gold2},
 practiceDistance:{height:82,marginTop:12,marginBottom:4,borderRadius:12,backgroundColor:C.white,borderWidth:1,borderColor:C.line,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:12},practiceStep:{width:38,height:38,borderRadius:9,backgroundColor:C.gold2,alignItems:'center',justifyContent:'center'},practiceStepText:{fontSize:24,fontWeight:'900',color:C.dark},practiceLabel:{fontSize:9,fontWeight:'900',textAlign:'center',color:C.muted,letterSpacing:1},practiceBig:{fontSize:30,fontWeight:'900',color:C.navy},
 checkRow:{flexDirection:'row',alignItems:'center',paddingVertical:11,paddingHorizontal:11,borderBottomWidth:1,borderBottomColor:'#DDD2BD'},checkBox:{width:28,height:28,borderRadius:7,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center',marginRight:10,backgroundColor:C.white},checkOn:{backgroundColor:C.gold2,borderColor:C.gold},checkMark:{fontSize:13,fontWeight:'900',color:C.dark},checkText:{fontSize:14,fontWeight:'800',color:C.navy},
 summaryHero:{backgroundColor:C.dark,borderWidth:1,borderColor:C.gold,borderRadius:14,padding:14,alignItems:'center',marginBottom:8},summaryScore:{fontSize:46,fontWeight:'900',color:C.gold2},summaryMeta:{fontSize:11,fontWeight:'700',color:C.white,marginTop:2},summaryRow:{flexDirection:'row',alignItems:'center',backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:9,padding:8,marginBottom:5},summaryHole:{width:27,fontSize:15,fontWeight:'900',color:C.navy},summaryText:{flex:1,fontSize:11,fontWeight:'600',color:C.text},
 courseBanner:{height:82,borderRadius:13,backgroundColor:'#45683F',borderWidth:1,borderColor:C.gold,alignItems:'center',justifyContent:'center',marginBottom:8},courseBannerFlag:{fontSize:28,color:C.gold2},courseBannerText:{fontSize:17,fontWeight:'900',color:C.white},facilityRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:5},facilityText:{fontSize:12,fontWeight:'800',color:C.navy}
});
